import { TaskProvider } from '@/context/TasksContext'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <TaskProvider>{children}</TaskProvider>
      </body>
    </html>
  )
}
